name: DumbWarp
main: com.turt2live.dumbwarp.DumbWarp
version: maven-version-number
description: I hate downloading plugins.
author: turt2live
website: http://github.com/turt2live/DumbWarp
build: jenkins-build-number
commands:
  setwarp:
    description: Sets a warp
  warp:
    description: Goes to a warp
  delwarp:
    description: Deletes a warp
  warps:
    description: Lists all known warps
permissions:
    DumbWarp.*:
      description: All DW commands
      default: op
      children:
        DumbWarp.warp: true
        DumbWarp.set: true
        DumbWarp.del: true
        DumbWarp.list: true
    DumbWarp.list:
      description: Allows /warps
      default: true
    DumbWarp.warp:
      description: Allows /warp
      default: true
    DumbWarp.set:
      description: Allows /setwarp
      default: op
    DumbWarp.del:
      description: Allows /delwarp
      default: op